
name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    # Runs a set of commands using the runners shell
    - name: BuildImage
      run: |
        mkdir -p /home/runner/gopath
        make buildImage
        make cert-manager-v1.19
      env:
       GOPATH: /home/runner/gopath
       GOBIN: /home/runner/gobin  

