
name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - name: Setup Go
      uses: actions/setup-go@v2.1.1
      with:
        go-version: 1.14



    # Runs a set of commands using the runners shell
    - name: BuildImage Kind image v1.19.0-rc.4
      run: |
        mkdir -p /home/runner/gopath
        GO111MODULE="off" go get k8s.io/kubernetes || true
        export GO111MODULE=on
        go get sigs.k8s.io/kind
        cd /home/runner/gopath/src/k8s.io/kubernetes && git checkout v1.19.0-rc.4
        kind build node-image --image=v1.19.0-rc.4
      env:
       GOPATH: /home/runner/gopath


